# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-06 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mysite.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=249)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', mysite.fields.ThumbnailImageField(upload_to='photos')),
                ('caption', models.CharField(blank=True, max_length=249)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.Item')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
