# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 14:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mysite.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u5730\u533a')),
            ],
            options={
                'verbose_name_plural': '\u5730\u533a\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='CatalogInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u7c7b\u578b')),
                ('remark', models.TextField(verbose_name='\u5907\u6ce8')),
            ],
            options={
                'verbose_name_plural': '\u7c7b\u578b\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='PlayerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, verbose_name='')),
                ('purl', models.CharField(max_length=255, verbose_name='')),
                ('name', models.CharField(max_length=255, verbose_name='')),
                ('restype', models.CharField(choices=[('XIGUA', '\u897f\u74dc\u7535\u5f71'), ('JIJI', '\u5409\u5409\u7535\u5f71'), ('ONLINE', '\u5728\u7ebf\u64ad\u653e')], max_length=10, verbose_name='')),
            ],
            options={
                'verbose_name_plural': '\u5206\u96c6\u7ba1\u7406',
            },
        ),
        migrations.CreateModel(
            name='ResourceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='\u7535\u5f71\u540d')),
                ('director', models.CharField(max_length=255, verbose_name='\u5bfc\u6f14')),
                ('screenwriter', models.CharField(max_length=255, verbose_name='\u7f16\u8f91')),
                ('actor', models.CharField(max_length=500, verbose_name='\u6f14\u5458')),
                ('language', models.CharField(max_length=255, verbose_name='\u8bed\u8a00')),
                ('time', models.DateField(verbose_name='\u4e0a\u6620\u65f6\u95f4')),
                ('length', models.IntegerField(verbose_name='\u7247\u957f')),
                ('othername', models.CharField(max_length=255, null=True, verbose_name='\u5176\u4ed6\u540d\u5b57')),
                ('score', models.FloatField(verbose_name='\u8bc4\u5206')),
                ('issuperme', models.BooleanField(default=False, verbose_name='\u662f\u5426\u7cbe\u9009')),
                ('restype', models.CharField(choices=[('MV', '\u7535\u5f71'), ('TV', '\u7535\u89c6\u5267')], max_length=100, verbose_name='\u8d44\u6e90\u7c7b\u578b')),
                ('picture', mysite.fields.ThumbnailImageField(blank=True, null=True, upload_to='covers', verbose_name='\u6d77\u62a5')),
                ('context', models.TextField(max_length=800, null=True, verbose_name='\u7b80\u4ecb')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie.AreaInfo', verbose_name='\u4ea7\u5730')),
                ('catalog', models.ManyToManyField(to='movie.CatalogInfo', verbose_name='\u5f71\u7247\u7c7b\u578b')),
            ],
            options={
                'verbose_name_plural': '\u8d44\u6e90\u7ba1\u7406',
            },
        ),
    ]
