# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-30 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20190530_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='qq',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='message',
            name='contents',
            field=models.TextField(),
        ),
    ]
